# ---------------------------------------
# Fenn Configuration (Modify Carefully)
# ---------------------------------------

project: mnist_mlp

logger:
  dir: logger

# ---------------------------------------
# User Section
# ---------------------------------------
general:
  device: cuda

checkpoint:
  name: mnist_mlp
  dir: ./models
  path: ./models/mnist_mlp_best.pt

train:
  seed: 42
  batch: 64
  epochs: 10
  lr: 0.001

test:
  batch: 64

val:
  batch: 64
